import { StyleSheet } from 'react-native';

const colors = {
  primary: '#6200ee',
  secondary: '#03dac4',
  backgroundLight: '#f0f0f0',
  backgroundDark: '#333',
  textPrimaryLight: '#333',
  textPrimaryDark: '#fff',
  textSecondary: '#fff',
  borderLight: '#ddd',
  borderDark: '#555',
  borderWhite: '#fff',
  shadow: '#000',
  inputBackgroundLight: '#fff',
  inputBackgroundDark: '#555',
};

const spacing = {
  small: 8,
  medium: 16,
  large: 24,
};

const fontSizes = {
  small: 14,
  medium: 16,
  large: 20,
};

const lightTheme = StyleSheet.create({
  container: {
    flex: 1,
    padding: spacing.large,
    backgroundColor: colors.backgroundLight,
  },
  headerContainer: {
    backgroundColor: colors.backgroundLight,
    padding: spacing.medium,
  },
  headerText: {
    fontSize: fontSizes.large,
    fontWeight: 'bold',
    color: colors.textPrimaryLight,
    textAlign: 'center',
  },
  inputWrapper: {
    marginBottom: spacing.large,
  },
  inputContainer: {
    flexDirection: 'column',
    alignItems: 'stretch',
    backgroundColor: colors.inputBackgroundLight,
    padding: spacing.medium,
    borderRadius: spacing.medium,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: spacing.medium,
    elevation: 2,
  },
  input: {
    height: 40,
    borderColor: colors.borderLight,
    borderWidth: 1,
    borderRadius: spacing.small,
    paddingLeft: spacing.medium,
    marginBottom: spacing.medium,
    color: colors.textPrimaryLight,
  },
  pickerButton: {
    backgroundColor: colors.inputBackgroundLight,
    padding: spacing.medium,
    borderRadius: spacing.small,
    borderColor: colors.borderLight,
    borderWidth: 1,
    marginBottom: spacing.medium,
  },
  pickerButtonText: {
    color: colors.textPrimaryLight,
  },
  picker: {
    height: 50,
    width: '100%',
  },
  singleCategoryText: {
    padding: spacing.medium,
    color: colors.textPrimaryLight,
    textAlign: 'center',
  },
  addButton: {
    backgroundColor: colors.primary,
    paddingVertical: spacing.small,
    paddingHorizontal: spacing.medium,
    borderRadius: spacing.small,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: spacing.small,
    elevation: 2,
  },
  addButtonText: {
    color: colors.textSecondary,
    fontSize: fontSizes.medium,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  list: {
    marginTop: spacing.large,
  },
  taskContainer: {
    backgroundColor: colors.inputBackgroundLight,
    padding: spacing.medium,
    marginVertical: spacing.small,
    borderRadius: spacing.medium,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: spacing.medium,
    elevation: 2,
    marginHorizontal: spacing.medium,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  taskText: {
    fontSize: fontSizes.medium,
    color: colors.textPrimaryLight,
  },
  categoryContainer: {
    backgroundColor: colors.secondary,
    padding: spacing.medium,
    marginVertical: spacing.small,
    borderRadius: spacing.medium,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: spacing.medium,
    elevation: 2,
    marginHorizontal: spacing.medium,
  },
  categoryText: {
    fontSize: fontSizes.medium,
    color: colors.textPrimaryLight,
  },
  background: {
    flex: 1,
    resizeMode: 'cover',
    justifyContent: 'center',
  },
  categorySection: {
    marginVertical: spacing.medium,
  },
  categoryHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: spacing.small,
    backgroundColor: colors.backgroundLight,
    borderRadius: spacing.medium,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: spacing.medium,
    elevation: 2,
    marginHorizontal: spacing.medium,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    backgroundColor: colors.inputBackgroundLight,
    padding: spacing.large,
    borderRadius: spacing.medium,
    width: '80%',
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: spacing.medium,
    elevation: 5,
  },
  deleteButton: {
    backgroundColor: 'red',
    paddingVertical: spacing.small,
    paddingHorizontal: spacing.medium,
    borderRadius: spacing.small,
    marginTop: spacing.medium,
  },
  deleteButtonText: {
    color: colors.textSecondary,
    fontSize: fontSizes.medium,
    fontWeight: 'bold',
    textAlign: 'center',
  },
});

const darkTheme = StyleSheet.create({
  container: {
    flex: 1,
    padding: spacing.large,
    backgroundColor: colors.backgroundDark,
  },
  headerContainer: {
    backgroundColor: colors.backgroundDark,
    padding: spacing.medium,
  },
  headerText: {
    fontSize: fontSizes.large,
    fontWeight: 'bold',
    color: colors.textPrimaryDark,
    textAlign: 'center',
  },
  inputWrapper: {
    marginBottom: spacing.large,
  },
  inputContainer: {
    flexDirection: 'column',
    alignItems: 'stretch',
    backgroundColor: colors.inputBackgroundDark,
    padding: spacing.medium,
    borderRadius: spacing.medium,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: spacing.medium,
    elevation: 2,
  },
  input: {
    height: 40,
    borderColor: colors.borderWhite,
    borderWidth: 1,
    borderRadius: spacing.small,
    paddingLeft: spacing.medium,
    marginBottom: spacing.medium,
    color: colors.textPrimaryDark,
  },
  pickerButton: {
    backgroundColor: colors.inputBackgroundDark,
    padding: spacing.medium,
    borderRadius: spacing.small,
    borderColor: colors.borderWhite,
    borderWidth: 1,
    marginBottom: spacing.medium,
  },
  pickerButtonText: {
    color: colors.textPrimaryDark,
  },
  picker: {
    height: 50,
    width: '100%',
  },
  singleCategoryText: {
    padding: spacing.medium,
    color: colors.textPrimaryDark,
    textAlign: 'center',
  },
  addButton: {
    backgroundColor: colors.primary,
    paddingVertical: spacing.small,
    paddingHorizontal: spacing.medium,
    borderRadius: spacing.small,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: spacing.small,
    elevation: 2,
  },
  addButtonText: {
    color: colors.textPrimaryDark,
    fontSize: fontSizes.medium,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  list: {
    marginTop: spacing.large,
  },
  taskContainer: {
    backgroundColor: colors.inputBackgroundDark,
    padding: spacing.medium,
    marginVertical: spacing.small,
    borderRadius: spacing.medium,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: spacing.medium,
    elevation: 2,
    marginHorizontal: spacing.medium,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  taskText: {
    fontSize: fontSizes.medium,
    color: colors.textPrimaryDark,
  },
  categoryContainer: {
    backgroundColor: colors.secondary,
    padding: spacing.medium,
    marginVertical: spacing.small,
    borderRadius: spacing.medium,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: spacing.medium,
    elevation: 2,
    marginHorizontal: spacing.medium,
  },
  categoryText: {
    fontSize: fontSizes.medium,
    color: colors.textPrimaryDark,
  },
  background: {
    flex: 1,
    resizeMode: 'cover',
    justifyContent: 'center',
  },
  categorySection: {
    marginVertical: spacing.medium,
  },
  categoryHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: spacing.small,
    backgroundColor: colors.backgroundDark,
    borderRadius: spacing.medium,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: spacing.medium,
    elevation: 2,
    marginHorizontal: spacing.medium,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    backgroundColor: colors.inputBackgroundDark,
    padding: spacing.large,
    borderRadius: spacing.medium,
    width: '80%',
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: spacing.medium,
    elevation: 5,
  },
  deleteButton: {
    backgroundColor: 'red',
    paddingVertical: spacing.small,
    paddingHorizontal: spacing.medium,
    borderRadius: spacing.small,
    marginTop: spacing.medium,
  },
  deleteButtonText: {
    color: colors.textSecondary,
    fontSize: fontSizes.medium,
    fontWeight: 'bold',
    textAlign: 'center',
  },
});

export default { lightTheme, darkTheme };
export { colors, spacing, fontSizes };
